BoxLayoutExample:

<BoxLayoutExample>:
    orientation: 'vertical'
    Button:
        text: 'A'
        #size: '100dp','80dp'
        #size_hint: 0.8, 0.5
        size_hint: None, 0.5
    Button:
        text: 'B'
    Label:
        text: 'C'


<MainWidget>:
    Button:
        text: 'siva1'
        size: '100dp','80dp'
        pos: '100dp','200dp'
        color: 0,0,1,1
    Label:
        text: 'siva2'
        size: '100dp','80dp'
        pos: '200dp','300dp'
        color: 1,0,0,1

